version: '3.1'

services:
  mysqldb:
    image: mysql
    container_name: mysql_pedido
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: